### ISSUE TITLE
reuse oscillator

### ISSUE THREAD

**Issue by laggingreflex** [laopunk/notePlayer#2]
`.play()` creates a new `oscillator` every time. Shouldn't it be created just once, and have it play/stop by just controlling `gain`? 

I could create a pull request but let me know if I'm mistaken, I'm relatively new to Web Audio.

(btw, great lib!)

**Comment by laopunk** [comment]
Hi @laggingreflex, sorry for the delay in responding.

The web audio API is designed and optimised to such a way that you can only use an oscillator once.  I am not sure why but we cannot go around it other than recreating the nodes every time.

That being said, it is very cheap and should not cause delays.

Let me know if you wish further enhancements on this lib
